### ISSUE TITLE
Update README with correct clone command

### ISSUE THREAD

**Issue by FalcoXYZ** [8ball030/AutonomousHegician#40]
@8ball030 can you confirm git clone git@github.com:8ball030/AutonomousHegician.git is the correct clone command? 
I believe you should use: git clone https://github.com/8ball030/AutonomousHegician.git

The current command doesn't work due to access right, second one works fine.

**Comment by andreiaugustin** [comment]
Should be fixed in pull request #44, the correct form is git clone git@github.com:8ball030/AutonomousHegician

**Comment by 8ball030** [comment]
@andreiaugustin is correct, closing with this
